SELECT DISTINCT JOB_ID "Job", (SELECT NVL(TO_CHAR(SUM(SALARY)), ' ') FROM EMPLOYEES WHERE JOB_ID = e.JOB_ID AND DEPARTMENT_ID = 20) "Dept 20",
(SELECT NVL(TO_CHAR(SUM(SALARY)), ' ') FROM EMPLOYEES WHERE JOB_ID = e.JOB_ID AND DEPARTMENT_ID = 50) "Dept 50",
(SELECT NVL(TO_CHAR(SUM(SALARY)), ' ') FROM EMPLOYEES WHERE JOB_ID = e.JOB_ID AND DEPARTMENT_ID = 80) "Dept 80",
(SELECT NVL(TO_CHAR(SUM(SALARY)), ' ') FROM EMPLOYEES WHERE JOB_ID = e.JOB_ID AND DEPARTMENT_ID = 90) "Dept 90",
(SELECT SUM(SALARY) FROM EMPLOYEES WHERE JOB_ID = e.JOB_ID) "Total"
FROM EMPLOYEES e ORDER BY JOB_ID;