SELECT DISTINCT (SELECT COUNT(*) FROM EMPLOYEES) TOTAL,
(SELECT COUNT(*) FROM EMPLOYEES WHERE HIRE_DATE LIKE '%95') "1995",
(SELECT COUNT(*) FROM EMPLOYEES WHERE HIRE_DATE LIKE '%96') "1996",
(SELECT COUNT(*) FROM EMPLOYEES WHERE HIRE_DATE LIKE '%97') "1997",
(SELECT COUNT(*) FROM EMPLOYEES WHERE HIRE_DATE LIKE '%98') "1998" FROM EMPLOYEES;