SELECT p.PRES_NAME, YRS_SERV, COUNT(SPOUSE_NAME), SUM(NR_CHILDREN) FROM PRESIDENT p
JOIN PRES_MARRIAGE pm ON p.PRES_NAME = pm.PRES_NAME
WHERE YRS_SERV >= 8 GROUP BY p.PRES_NAME, YRS_SERV HAVING COUNT(SPOUSE_NAME) >= 2;