SELECT PRES_NAME FROM PRESIDENT p
JOIN ELECTION e ON p.PRES_NAME = e.CANDIDATE
WHERE ELECTION_YEAR - BIRTH_YR =
(SELECT MIN(ELECTION_YEAR - BIRTH_YR) FROM PRESIDENT p
JOIN ELECTION e ON p.PRES_NAME = e.CANDIDATE);