//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficMessageSender.TrafficMessageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MessageService", ConfigurationName="TrafficMessageService.ITrafficMessage")]
    public interface ITrafficMessage {
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/GetServerName", ReplyAction="MessageService/ITrafficMessage/GetServerNameResponse")]
        string GetServerName();
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/SendRedLight", ReplyAction="MessageService/ITrafficMessage/SendRedLightResponse")]
        void SendRedLight(int carID, int trafficLightID, System.DateTime time);
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/SendAccident", ReplyAction="MessageService/ITrafficMessage/SendAccidentResponse")]
        void SendAccident(int junctionID, System.DateTime time);
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/SendSpeeding", ReplyAction="MessageService/ITrafficMessage/SendSpeedingResponse")]
        void SendSpeeding(int carID, int carSpeed, System.DateTime time);
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/RetrieveMessage", ReplyAction="MessageService/ITrafficMessage/RetrieveMessageResponse")]
        string RetrieveMessage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrafficMessageChannel : TrafficMessageSender.TrafficMessageService.ITrafficMessage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrafficMessageClient : System.ServiceModel.ClientBase<TrafficMessageSender.TrafficMessageService.ITrafficMessage>, TrafficMessageSender.TrafficMessageService.ITrafficMessage {
        
        public TrafficMessageClient() {
        }
        
        public TrafficMessageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrafficMessageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrafficMessageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrafficMessageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetServerName() {
            return base.Channel.GetServerName();
        }
        
        public void SendRedLight(int carID, int trafficLightID, System.DateTime time) {
            base.Channel.SendRedLight(carID, trafficLightID, time);
        }
        
        public void SendAccident(int junctionID, System.DateTime time) {
            base.Channel.SendAccident(junctionID, time);
        }
        
        public void SendSpeeding(int carID, int carSpeed, System.DateTime time) {
            base.Channel.SendSpeeding(carID, carSpeed, time);
        }
        
        public string RetrieveMessage() {
            return base.Channel.RetrieveMessage();
        }
    }
}
