CREATE OR REPLACE TRIGGER YEARS_SERVED_DECREASE_CHECK
AFTER UPDATE OF YRS_SERV ON PRESIDENT
FOR EACH ROW
BEGIN
    IF(:NEW.YRS_SERV < :OLD.YRS_SERV) THEN
    RAISE_APPLICATION_ERROR(-20001, 'Years of serving of presidents cannot be decreased.');
    END IF;
END;
/