INSERT INTO PRES_HOBBY
(PRES_NAME, HOBBY) VALUES('ADAMS J Q', 'GOLF');
INSERT INTO PRES_HOBBY
(PRES_NAME, PRES_HOBBY) VALUES('ADAMS J Q', 'HUNTING');
INSERT INTO PRES_HOBBY
(PRES_NAME, PRES_HOBBY) VALUES('ADAMS J Q', 'PAINTING');
INSERT INTO PRES_HOBBY
(PRES_NAME, PRES_HOBBY) VALUES('ADAMS J Q', 'SHOOTING');