CREATE OR REPLACE TRIGGER INAUGURATION_YEAR_CHECK
BEFORE INSERT OR UPDATE OF YEAR_INAUGURATED ON ADMINISTRATION
FOR EACH ROW
DECLARE
    yearOfBirth NUMBER;
BEGIN
    SELECT BIRTH_YR INTO yearOfBirth
    FROM PRESIDENT
    WHERE PRES_NAME = :NEW.PRES_NAME;
    
    IF (:NEW.YEAR_INAUGURATED - yearOfBirth < 21) THEN
        RAISE_APPLICATION_ERROR(-20004, 'A president should be at least 21 years old by the date of inauguration.');
    END IF;
END;
/