CREATE OR REPLACE TRIGGER ELECTION_WINNER_CHECK
BEFORE INSERT OR UPDATE OF WINNER_LOSER_INDIC ON ELECTION
FOR EACH ROW
DECLARE
    winner NUMBER(1);
BEGIN
    SELECT COUNT(WINNER_LOSER_INDIC) INTO winner
    FROM ELECTION
    WHERE ELECTION_YEAR = :NEW.ELECTION_YEAR;
    
    IF (winner > 0 AND :NEW.WINNER_LOSER_INDIC = 'W') THEN
        RAISE_APPLICATION_ERROR(-20005, 'An election can have only one winner.');
    END IF;
END;
/